version: '3.5'

services:

  nginx:
    image: nginx
    ports:
      - 8080:80
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://192.168.50.200:9522"



  redis:
    image: redis
    ports:
      - 6379:6379
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://192.168.50.200:9511"
